### ISSUE TITLE
ZX Spectrum core doesn't work

### ISSUE THREAD

**Issue by sorgelig** [mist-devel/mist-board#10] opened 2015-11-29 19:22 UTC
Hi!
Not sure where to get support for this, but none of ZX core binaries work with either latest firmware and 20150910. Since 20150910 is the minimum required for Amiga AGA core i cannot go to earlier versions.

Oldest available ZX core doesn't support RGBS mode, but it seams shows some start Spectrum dialog. I cannot use it because my scaler cannot sync doublescan frequency. From second to latest ZX cores hang on startup with garbage on screen.

Is it possible to get updated (may be simple re-compilation required?) ZX core binary?

**Comment by harbaum** [comment] 2015-11-30 11:55
Duplicate of https://github.com/mist-devel/mist-binaries/issues/2

Please re-open that one if you still need help.Thanks.

**Closed as completed by harbaum** 2015-11-30 11:55 UTC
